# Generated by Django 2.1.5 on 2019-01-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='c1Cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='c2Cnt',
            field=models.IntegerField(default=0),
        ),
    ]
